/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superchatearningsgui;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 *
 * @author Pinapelz
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        videoURL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        jButton2.setText("Set Currency File");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Video URL");

        videoURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoURLActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("How much did they make?");

        jButton1.setText("Set Currency File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        messageArea.setEditable(false);
        messageArea.setColumns(20);
        messageArea.setRows(5);
        jScrollPane1.setViewportView(messageArea);

        outputArea.setEditable(false);
        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane2.setViewportView(outputArea);

        jButton3.setText("CALCULATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(videoURL))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(videoURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Code below grabs chat and only adds members and superchats into a txt file 
        //Then it throws every single one of those lines into an ArrayList
        messageArea.setText(null);
        int members = 0;
        String streamLength = "";
        ArrayList<String> superchat = new ArrayList<String>();
        File del = new File("money.txt");
        if (del.delete()) {
            System.out.println("Deleted the file: " + del.getName());
        } else {
            System.out.println("Failed to delete the file.");
        }
        Process p;
        ArrayList<String> profit = new ArrayList();
        try {
            ProcessBuilder builder = new ProcessBuilder("cmd.exe", "/C", "python3 collectChat.py " + videoURL.getText());
            builder.redirectOutput(new File("earnings2.txt"));
            builder.redirectError(new File("error.txt"));
            p = builder.start(); // may throw IOException
            int exitVal = p.waitFor();

            BufferedReader bufReader = new BufferedReader(new FileReader("earnings2.txt"));

            String line = bufReader.readLine();
            while (line != null) {
                profit.add(line);

                messageArea.setText(messageArea.getText() + line + "\n");
                line = bufReader.readLine();
            }
            streamLength = line.substring(0, line.indexOf("|"));
            bufReader.close();
        } catch (Exception ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);

        }
        System.out.println("Now crunching the numbers!");
        Pattern pattern = Pattern.compile("\\*(.*?)\\*");
        for (int i = 0; i < profit.size(); i++) {
            try {
                Matcher matcher = pattern.matcher(profit.get(i));
                matcher.find();
                superchat.add(fixCurrency(matcher.group(1)));

            } catch (Exception e) {
                members++;
            }
        }
        ArrayList<Double> numericalUSD = new ArrayList<Double>();
        try {
            HashMap<String, String> exchange = hashmapReturn();
            ArrayList<String> currency = new ArrayList<String>();
            ArrayList<String> exchangeRate = new ArrayList<String>();
            currency.addAll(exchange.keySet());
            exchangeRate.addAll(exchange.values());

            for (int i = 0; i < superchat.size(); i++) {
                boolean matched = false;
                for (int j = 0; j < currency.size(); j++) {
                    if (superchat.get(i).contains(currency.get(j))) {
                        double temp = Double.parseDouble(superchat.get(i).replaceAll("[^\\d.]", ""));
                        double exchanged = Double.parseDouble(exchange.get(currency.get(j)));
                        numericalUSD.add(temp * exchanged);
                        matched = true;
                        break;
                    }

                }
                if (matched == false) {
                    numericalUSD.add(Double.parseDouble(superchat.get(i).replaceAll("[^\\d.]", "")));
                }
            }
            double totalSum = 0;
            for (int i = 0; i < numericalUSD.size(); i++) {
                System.out.println(numericalUSD.get(i));
                totalSum = totalSum + numericalUSD.get(i);

            }
            NumberFormat defaultFormat = NumberFormat.getCurrencyInstance();
            
           
   
            outputArea.setText(
                      "Total Stream Length: " + streamLength
                    + "\nTotal Superchat Earnings: " + defaultFormat.format(totalSum) + " USD"    
                    + "\n Total New Members: " + members + " ($" + members * 4 + ")"
                    + "\nGrand Total: " + defaultFormat.format((double) ((members * 4) + totalSum)) + " USD");

        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton3ActionPerformed
    public String fixCurrency(String str) {
        str = str.replaceAll("R$", "BRS");
        str = str.replaceAll("₽", "RUB");
        str = str.replaceAll("USh", "UGX");
        str = str.replaceAll("₪", "ISK");
        str = str.replaceAll("€", "EUR");
        str = str.replaceAll("£", "GBP");
        str = str.replaceAll("₩", "KRW");
        str = str.replaceAll("CA", "CAD");
        str = str.replaceAll("NT", "TWD");
        str = str.replaceAll("¥", "JPY");
        str = str.replaceAll("HK", "HKD");
        str = str.replaceAll("NZ", "NZD");
        str = str.replaceAll("MX", "MXN");
        str = str.replaceAll("₱", "PHP");
        str = str.replaceAll("S/", "PEN");
        str = str.replaceAll("$U", "UYU");
        if (str.startsWith("A$")) {
            str = str.replaceAll("A$", "AUD");
        }
        str = str.replaceAll("\\$", "");

        return str;
    }

    public HashMap<String, String> hashmapReturn() throws FileNotFoundException, IOException {
        String filePath = "currency.txt";
        HashMap<String, String> map = new HashMap<String, String>();

        String line;
        BufferedReader reader = new BufferedReader(new FileReader(filePath));
        while ((line = reader.readLine()) != null) {
            String[] parts = line.split(":", 2);
            if (parts.length >= 2) {
                String key = parts[0];
                String value = parts[1];
                map.put(key, value);
            } else {
                System.out.println("ignoring line: " + line);
            }
        }

        reader.close();
        return map;
    }
    private void videoURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_videoURLActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JTextField videoURL;
    // End of variables declaration//GEN-END:variables
}
